pages:
  script:
  - apt-get update
  - apt install pip
  - apt install make
  - pip install sphinx
  - pip install numpy
  - pip install scipy
  - pip install matplotlib
  - pip install corner
  - cd doc/
  - make html
  - mv build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
